# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-12 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_cashtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletransaction',
            name='creditcardtransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.CreditCardTransaction'),
        ),
    ]
