# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-12 07:55
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20180612_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from=b'name', unique=True),
        ),
    ]
