# Generated by Django 4.0.5 on 2022-09-09 12:53

import autoslug.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance_at', models.DateField()),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('transaction_type', models.CharField(choices=[('single', 'Single'), ('income', 'Income'), ('utility', 'Utility'), ('debt', 'Debt'), ('creditcard', 'Credit Card'), ('unknown', 'Unknown')], default='debt', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='web.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.transaction')),
                ('started_at', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('cycle_due_date', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-yearly', 'Semi-Yearly'), ('yearly', 'Yearly')], default='monthly', max_length=50)),
                ('is_variable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('web.transaction',),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
                ('record_count', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedfiles', to='web.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('account_type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ref', models.CharField(max_length=255)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('debits', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('record_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='web.recordgroup')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='web.transaction')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='records', to='web.uploadedfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overpayment', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payment_at', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannedplayments', to='web.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('recurringtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.recurringtransaction')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cycle_billing_date', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
            options={
                'abstract': False,
            },
            bases=('web.recurringtransaction',),
        ),
        migrations.CreateModel(
            name='DebtTransaction',
            fields=[
                ('recurringtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.recurringtransaction')),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('principal_at', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('web.recurringtransaction',),
        ),
        migrations.CreateModel(
            name='SingleTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.transaction')),
                ('transaction_at', models.DateField()),
                ('creditcardtransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singletransactions', to='web.creditcardtransaction')),
            ],
            options={
                'abstract': False,
            },
            bases=('web.transaction',),
        ),
        migrations.CreateModel(
            name='CreditCardExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('creditcardtransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditcardexpenses', to='web.creditcardtransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
