# Generated by Django 4.0.5 on 2022-09-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordgroup',
            name='stats',
            field=models.JSONField(null=True),
        ),
    ]
