# Generated by Django 4.0.5 on 2022-09-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_recordgroup_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=255)),
                ('is_rented', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_category',
            field=models.CharField(choices=[['tax', '<built-in method upper of str object at 0x7f99af50b370>ax;'], ['utility', '<built-in method upper of str object at 0x7f99af511430>tility;'], ['repair', '<built-in method upper of str object at 0x7f99af4d65f0>epair;'], ['maintenance', '<built-in method upper of str object at 0x7f99af5362f0>aintenance;'], ['insurance', '<built-in method upper of str object at 0x7f99af4a7430>nsurance;']], default='maintenance', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='web.property'),
        ),
    ]
