# Generated by Django 4.0.5 on 2022-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_property_transaction_tax_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_category',
            field=models.CharField(choices=[['none', 'None'], ['tax', 'Tax'], ['utility', 'Utility'], ['repair', 'Repair'], ['maintenance', 'Maintenance'], ['insurance', 'Insurance']], default='none', max_length=50, null=True),
        ),
    ]
