# Generated by Django 4.0.5 on 2022-09-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_uploadedfile_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
