# Generated by Django 4.0.5 on 2022-09-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_account_csv_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='first_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='last_date',
            field=models.DateField(null=True),
        ),
    ]
