# Generated by Django 4.0.5 on 2022-09-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_transaction_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='csv_date_format',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
