# Generated by Django 4.0.5 on 2022-09-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_account_csv_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='extra_fields',
            field=models.JSONField(null=True),
        ),
    ]
