# Generated by Django 4.0.5 on 2022-09-13 02:01

from django.conf import settings 
from django.db import migrations
from decimal import Decimal

def forwards_func(apps, schema_editor):
    Record = apps.get_model("web", "Record")
    for record in Record.objects.all():
        record.extra_fields = {}
        for field in ['type', 'account_type', 'ref', 'credits', 'debits']:
            field_val = record.__getattribute__(field)
            if field in ['credits', 'debits'] and type(field_val) == Decimal:
                field_val = f'{float(field_val):.2f}'
            record.extra_fields[field] = field_val
        record.save()
    
def reverse_func(apps, schema_editor):
    Record = apps.get_model("web", "Record")
    for record in Record.objects.all():
        for field in ['type', 'account_type', 'ref', 'credits', 'debits']:
            record.__setattr__(field, record.extra_fields[field])
        record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_record_extra_fields'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
