# Generated by Django 4.0.5 on 2022-09-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_record_extra_field_consolidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.account'),
        ),
    ]
