# Generated by Django 4.0.5 on 2022-09-14 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_record_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('csv_columns', models.CharField(max_length=1024, null=True)),
                ('csv_date_format', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='records', to='web.account'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadedfiles', to='web.account'),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recordtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='creditcards', to='web.recordtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='recordtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', to='web.recordtype'),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='creditcard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='creditcardtransactions', to='web.creditcard'),
        ),
        migrations.AddField(
            model_name='record',
            name='creditcard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='records', to='web.creditcard'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='creditcard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploadedfiles', to='web.creditcard'),
        ),
    ]
