# Generated by Django 4.0.5 on 2022-09-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_populate_recordtype_and_creditcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='csv_columns',
        ),
        migrations.RemoveField(
            model_name='account',
            name='csv_date_format',
        ),
        migrations.RemoveField(
            model_name='creditcardtransaction',
            name='interest_rate',
        ),
    ]
