# Generated by Django 4.0.5 on 2022-09-14 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_account_csv_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='cycle_billing_date',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='cycle_due_date',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='account_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
