# Generated by Django 4.0.5 on 2022-09-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_creditcard_cycle_billing_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='date',
            new_name='transaction_date',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadedfiles', to='web.account'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='creditcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploadedfiles', to='web.creditcard'),
        ),
    ]
