# Generated by Django 4.0.5 on 2022-09-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_rename_date_record_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='post_date',
            field=models.DateField(null=True),
        ),
    ]
