# Generated by Django 4.0.5 on 2022-09-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='creditcardexpense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='web.creditcardexpense'),
        ),
    ]
