# Generated by Django 4.0.5 on 2022-09-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_transactionruleset_transactionrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionruleset',
            name='join_operator',
            field=models.CharField(choices=[['and', 'And'], ['or', 'Or']], max_length=3),
        ),
    ]
