# Generated by Django 4.0.5 on 2022-09-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_transactionruleset_join_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionruleset',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='period',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-yearly', 'Semi-Yearly'), ('yearly', 'Yearly')], default='monthly', max_length=50),
        ),
    ]
