# Generated by Django 4.0.5 on 2022-09-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_transactionruleset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrule',
            name='match_operator',
            field=models.CharField(choices=[('>', '<'), ('=', '='), ('>', '>'), ('contains', 'contains')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactionruleset',
            name='name',
            field=models.CharField(default='blank', max_length=255),
            preserve_default=False,
        ),
    ]
