# Generated by Django 4.0.5 on 2022-09-28 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_transactionrule_match_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityTransaction',
            fields=[
                ('recurringtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.recurringtransaction')),
            ],
            options={
                'abstract': False,
            },
            bases=('web.recurringtransaction',),
        ),
        migrations.AlterField(
            model_name='transactionrule',
            name='match_operator',
            field=models.CharField(choices=[('>', '>'), ('=', '='), ('<', '<'), ('contains', 'contains')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProtoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('tax_category', models.CharField(choices=[['none', 'None'], ['tax', 'Tax'], ['utility', 'Utility'], ['repair', 'Repair'], ['maintenance', 'Maintenance'], ['insurance', 'Insurance']], default='none', max_length=50, null=True)),
                ('transaction_type', models.CharField(choices=[('single', 'Single'), ('income', 'Income'), ('utility', 'Utility'), ('debt', 'Debt'), ('creditcard', 'Credit Card'), ('unknown', 'Unknown')], default='debt', max_length=50)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototransactions', to='web.account')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototransactions', to='web.property')),
                ('transactionruleset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prototransaction', to='web.transactionruleset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='prototransaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='web.prototransaction'),
        ),
    ]
