# Generated by Django 4.0.5 on 2022-09-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_prototransaction_transactionruleset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionruleset',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
