# Generated by Django 4.0.5 on 2022-09-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_remove_record_account_type_remove_record_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototransaction',
            name='period',
            field=models.CharField(choices=[['unknown', 'Unknown'], ['weekly', 'Weekly'], ['bi-weekly', 'Bi-weekly'], ['monthly', 'Monthly'], ['quarterly', 'Quarterly'], ['semiannually', 'Semiannually'], ['yearly', 'Yearly']], default='monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='prototransaction',
            name='transaction_type',
            field=models.CharField(choices=[['single', 'Single'], ['income', 'Income'], ['utility', 'Utility'], ['debt', 'Debt'], ['creditcard', 'Creditcard'], ['unknown', 'Unknown']], default='debt', max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='period',
            field=models.CharField(choices=[['unknown', 'Unknown'], ['weekly', 'Weekly'], ['bi-weekly', 'Bi-weekly'], ['monthly', 'Monthly'], ['quarterly', 'Quarterly'], ['semiannually', 'Semiannually'], ['yearly', 'Yearly']], default='monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[['single', 'Single'], ['income', 'Income'], ['utility', 'Utility'], ['debt', 'Debt'], ['creditcard', 'Creditcard'], ['unknown', 'Unknown']], default='debt', max_length=50),
        ),
    ]
