# Generated by Django 4.0.5 on 2023-08-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_prototransaction_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototransaction',
            name='period',
            field=models.CharField(choices=[['unknown', 'Unknown'], ['daily', 'Daily'], ['weekly', 'Weekly'], ['bi-weekly', 'Bi-weekly'], ['monthly', 'Monthly'], ['quarterly', 'Quarterly'], ['semiannually', 'Semiannually'], ['yearly', 'Yearly']], default='monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='period',
            field=models.CharField(choices=[['unknown', 'Unknown'], ['daily', 'Daily'], ['weekly', 'Weekly'], ['bi-weekly', 'Bi-weekly'], ['monthly', 'Monthly'], ['quarterly', 'Quarterly'], ['semiannually', 'Semiannually'], ['yearly', 'Yearly']], default='monthly', max_length=50),
        ),
    ]
