# Generated by Django 4.0.5 on 2023-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_alter_prototransaction_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionruleset',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
