# Generated by Django 4.0.5 on 2023-08-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_transactionruleset_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='header_included',
            field=models.BooleanField(default=True),
        ),
    ]
