# Generated by Django 4.0.5 on 2023-08-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_uploadedfile_header_included'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_group',
        ),
        migrations.DeleteModel(
            name='RecordGroup',
        ),
    ]
