# Generated by Django 4.0.5 on 2023-08-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_remove_record_record_group_delete_recordgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='record',
            name='account',
        ),
        migrations.RemoveField(
            model_name='record',
            name='creditcard',
        ),
        migrations.RemoveField(
            model_name='record',
            name='transaction',
        ),
    ]
