# Generated by Django 4.0.5 on 2023-08-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_remove_prototransaction_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrule',
            name='inclusion',
            field=models.CharField(choices=[['exclude', 'Exclude'], ['filter', 'Filter']], default='filter', max_length=10),
        ),
    ]
