# Generated by Django 4.0.5 on 2023-08-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_transactionrule_inclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrule',
            name='match_operator',
            field=models.CharField(choices=[('>', '>'), ('=', '='), ('<', '<'), ('contains', 'contains'), ('regex', 'regex')], max_length=20, null=True),
        ),
    ]
