# Generated by Django 4.0.5 on 2023-08-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_record_credit_record_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
