# Generated by Django 4.0.5 on 2023-08-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_record_credit_alter_record_debit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='creditcardexpense',
        ),
    ]
