# Generated by Django 4.0.5 on 2023-08-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_remove_record_creditcardexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='record',
            name='debit',
        ),
        migrations.AddField(
            model_name='recordtype',
            name='flow_convention',
            field=models.CharField(choices=[['normal', 'Normal'], ['reverse', 'Reverse']], default='normal', max_length=10),
        ),
    ]
