# Generated by Django 4.0.5 on 2023-08-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_remove_record_credit_remove_record_debit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prototransaction',
            old_name='amount',
            new_name='recurring_amount',
        ),
    ]
