# Generated by Django 4.0.5 on 2023-08-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_rename_amount_prototransaction_recurring_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordType',
            new_name='RecordFormat',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='recordtype',
            new_name='recordformat',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='recordtype',
            new_name='recordformat',
        ),
    ]
