# Generated by Django 4.0.5 on 2023-08-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_rename_recordtype_recordformat_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['description'], name='web_record_descrip_5277ca_idx'),
        ),
    ]
