# Generated by Django 4.0.5 on 2023-08-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_record_web_record_descrip_5277ca_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[['unknown', 'Unknown'], ['refund', 'Refund'], ['income', 'Income'], ['expense', 'Expense'], ['penalty', 'Penalty'], ['internal', 'Internal']], default='unknown', max_length=15),
        ),
    ]
