# Generated by Django 4.0.5 on 2023-08-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_record_record_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('extra_fields_hash', models.CharField(max_length=32, null=True)),
                ('record_type', models.CharField(choices=[['unknown', 'Unknown'], ['refund', 'Refund'], ['income', 'Income'], ['expense', 'Expense'], ['penalty', 'Penalty'], ['internal', 'Internal']], default='unknown', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='record',
            name='extra_fields_hash',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
