# Generated by Django 4.0.5 on 2023-08-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_auto_20230827_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_type',
        ),
    ]
