# Generated by Django 4.0.5 on 2023-08-31 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_recordmeta_detailed_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordmeta',
            old_name='detailed_description',
            new_name='detail',
        ),
    ]
