# Generated by Django 4.0.5 on 2023-09-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_rename_detailed_description_recordmeta_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototransaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prototransaction',
            name='timing',
            field=models.CharField(choices=[['periodic', 'Periodic'], ['chaotic', 'Chaotic'], ['chaotic', 'Chaotic'], ['single', 'Single']], default='single', max_length=20),
        ),
    ]
