# Generated by Django 4.0.5 on 2023-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_prototransaction_is_active_prototransaction_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(choices=[['working_bracket', 'Working_bracket']], default='null', max_length=255)),
                ('value', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
