# Generated by Django 4.0.5 on 2023-09-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_prototransaction_is_active_prototransaction_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordformat',
            name='csv_date_format',
            field=models.CharField(default='%m/%d/%Y', max_length=20),
        ),
    ]
