# Generated by Django 4.0.5 on 2023-09-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='prototransaction',
            name='property',
        ),
        migrations.AddField(
            model_name='recordmeta',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordmetas', to='web.property'),
        ),
        migrations.AddField(
            model_name='recordmeta',
            name='target',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recordmeta',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordmetas', to='web.vehicle'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(choices=[('working_bracket', 'working bracket')], default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='recordmeta',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordmetas', to='web.event'),
        ),
    ]
