# Generated by Django 4.0.5 on 2023-09-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_event_remove_prototransaction_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmeta',
            name='is_accounted',
            field=models.BooleanField(default=False),
        ),
    ]
