# Generated by Django 4.0.5 on 2023-09-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_alter_recordformat_csv_date_format'),
        ('web', '0056_recordmeta_is_accounted'),
    ]

    operations = [
    ]
