# Generated by Django 4.0.5 on 2023-09-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_alter_record_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmeta',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
