# Generated by Django 4.0.5 on 2023-09-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_alter_recordmeta_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordmeta',
            name='is_accounted',
        ),
        migrations.AddField(
            model_name='recordmeta',
            name='accounted_at',
            field=models.IntegerField(default=0),
        ),
    ]
