# Generated by Django 4.0.5 on 2023-09-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_remove_recordmeta_is_accounted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='core_fields_hash',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recordmeta',
            name='core_fields_hash',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
