# Generated by Django 4.0.5 on 2023-09-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_record_core_fields_hash_recordmeta_core_fields_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmeta',
            name='accounted_at',
            field=models.IntegerField(null=True),
        ),
    ]
