# Generated by Django 4.0.5 on 2023-09-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_record_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='accounted_at',
            field=models.IntegerField(null=True),
        ),
    ]
