# Generated by Django 4.0.5 on 2023-09-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_record_accounted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['record_type', 'accounted_at'], name='web_record_record__92c5a4_idx'),
        ),
    ]
