# Generated by Django 4.0.5 on 2023-09-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_record_web_record_record__92c5a4_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['core_fields_hash'], name='web_record_core_fi_1ececd_idx'),
        ),
        migrations.AddIndex(
            model_name='recordmeta',
            index=models.Index(fields=['core_fields_hash'], name='web_recordm_core_fi_17f79a_idx'),
        ),
    ]
