# Generated by Django 4.0.5 on 2023-09-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_record_web_record_core_fi_1ececd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='record',
            name='web_record_record__92c5a4_idx',
        ),
        migrations.RemoveField(
            model_name='record',
            name='accounted_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_type',
        ),
    ]
