# Generated by Django 4.0.5 on 2023-09-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_remove_record_web_record_record__92c5a4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordmeta',
            name='accounted_at',
        ),
    ]
