# Generated by Django 4.0.5 on 2023-09-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_remove_recordmeta_accounted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['extra_fields_hash'], name='web_record_extra_f_f64775_idx'),
        ),
    ]
