# Generated by Django 4.0.5 on 2023-09-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_record_web_record_extra_f_f64775_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='started_at',
            field=models.DateField(null=True),
        ),
    ]
