# Generated by Django 4.0.5 on 2023-10-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0074_record_raw_data_line_record_raw_data_line_hash_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['raw_data_line_hash'], name='web_record_raw_dat_76bbed_idx'),
        ),
        migrations.AddIndex(
            model_name='recordmeta',
            index=models.Index(fields=['raw_data_line_hash'], name='web_recordm_raw_dat_14f9cf_idx'),
        ),
    ]
