# Generated by Django 4.0.5 on 2023-10-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0075_record_web_record_raw_dat_76bbed_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['core_fields_hash', 'raw_data_line_hash'], name='web_record_core_fi_26c0b3_idx'),
        ),
        migrations.AddIndex(
            model_name='recordmeta',
            index=models.Index(fields=['core_fields_hash', 'raw_data_line_hash'], name='web_recordm_core_fi_fa5249_idx'),
        ),
    ]
