# Generated by Django 4.0.5 on 2023-10-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0077_record_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototransaction',
            name='monthly_earn',
        ),
        migrations.RemoveField(
            model_name='prototransaction',
            name='monthly_spend',
        ),
    ]
