# Generated by Django 4.0.5 on 2023-10-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0080_prototransaction_criticality'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototransaction',
            name='direction',
            field=models.CharField(choices=[['credit', 'Credit'], ['debit', 'Debit'], ['bidirectional', 'Bidirectional'], ['unset', 'Unset']], default='unset', max_length=20),
        ),
    ]
