# Generated by Django 4.0.5 on 2023-10-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0081_prototransaction_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototransaction',
            name='period',
        ),
    ]
