# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-12 06:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20180612_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from=b'name', unique=False),
        ),
    ]
